spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - path=/api/user/**

        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
              - path=/api/hotel/**


        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - path=/api/rating/**
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
